source 'https://rubygems.org'

gem 'jekyll'

group :jekyll_plugins do
  gem 'jekyll-gist'
  gem 'jekyll-paginate'
  gem "jekyll-asciidoc"
end

gem 'asciidoctor', '~> 1.5.4'
gem 'bigdecimal'
gem 'coderay', '1.1.1'
gem 'base64'
gem 'csv'
gem 'logger'
